version: 0.1
namespaces:
  default:
    ".env":
      driver: "local"
      args:
        ext: ".env"
        transform:
          read: dotenv
          write: dotenv
        root: "."
      mount:
        # dir: ""
        file: ""

    "vault":
      driver: vault
      args:
        conn:
          addr: "http://localhost:8200"
          token: root
          mount: secret
        transform:
          read: null
          write: null
        root: app/prod

    "test":
      driver: "local"
      args:
        transform:
          read: dotenv
          write: dotenv
        root: "."
      mount:
        file: ""
