version: 0.1
namespaces:
  default:
    .env:
      backend:
        type: local
        args:
          type: .env
      args:
        dir: .
        file: ""
    vault:
      backend:
        type: vault
        args:
          addr: http://localhost:8200
          token: root
          namespace: ""
      args:
        mountpoint: secret
        dir: app
        file: prod
    db:
      backend:
        type: db
        subtype: postgres
        args:
          query: "select key, value from configs where key = :namespace + '/' + :key"
